# Generated by Django 4.1.3 on 2022-11-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
