# Generated by Django 4.1.3 on 2022-11-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aluno_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='status_emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status_emprestimo',
            field=models.CharField(choices=[('APROVADO', 'APROVADO'), ('REJEITADO', 'REJEITADO')], default=2, max_length=150),
            preserve_default=False,
        ),
    ]
