# Generated by Django 4.1.3 on 2022-11-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_livro_status_emprestimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='genero',
        ),
    ]
