# Generated by Django 4.1.3 on 2022-11-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_emprestimo_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status_emprestimo',
            field=models.CharField(choices=[('APROVADO', 'APROVADO'), ('REJEITADO', 'REJEITADO'), ('DEVOLVIDO', 'DEVOLVIDO')], max_length=150),
        ),
    ]
